# Generated by Django 5.2.7 on 2025-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='care_tips',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disease',
            name='healthy_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
